baseurl: "/"
languageCode: "en-us"
title: "Weazel News RP"
theme: "hugo-xmag"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
hasCJKLanguage: true
enableEmoji: true
paginate: 6

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Contributing
      url: /contributing/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: About
      url: /about/
      weight: 5


params:
  description: "Weazel News, Confirming your prejudices!"
  footer: "&copy; [Weazel News RP](https://legit.weazelrp.news) 2021 | [Discord](https://discord.legitrp.com)"
  summary_length: 300
  text:
    back: "&larr; Back to Home"
    edit: "Edit this page &rarr;"
    truncated: "&hellip;"

markup:
  goldmark:
    renderer:
      unsafe: true
